$schema: http://json-schema.org/draft-07/schema#
type: object
properties:
  setup:
    type: object
    properties:
      spindle_speed:
        type: object
        properties:
          max:
            anyOf:
              - type: "number"
              - type: "string"
                pattern: "^(?:\\d+(?:\\.\\d+)?)(?:rpm)$"
            default: 24000
            description: "Maximum spindle speed in RPM."
            minimum: 0
          min:
            anyOf:
              - type: "number"
              - type: "string"
                pattern: "^(?:\\d+(?:\\.\\d+)?)(?:rpm)$"
            default: 10000
            description: "Minimum spindle speed in RPM."
            minimum: 0
        required: [max, min]
        description: "Practical spindle limits in RPM."
      z_feedrate:
        type: object
        properties:
          min:
            anyOf:
              - type: "number"
              - type: "string"
                pattern: "^(?:\\d+(?:\\.\\d+)?)(?:mm\\/min|cm\\/min|in\\/min|inch\\/min|mil\\/min|thou\\/min)$"
            default: 200
            description: "Minimum Z feedrate."
            minimum: 0
          max:
            anyOf:
              - type: "number"
              - type: "string"
                pattern: "^(?:\\d+(?:\\.\\d+)?)(?:mm\\/min|cm\\/min|in\\/min|inch\\/min|mil\\/min|thou\\/min)$"
            default: 4000
            description: "Maximum Z feedrate."
            minimum: 0
        required: [min, max]
        description: "Practical CNC limits."
      safe_distance:
        type: "string"
        pattern: "^(?:\\d+(?:\\.\\d+)?|\\d+\\/\\d+)(?:mm|cm|in|inch|mil|thou)$"
        default: "0.5mm"
        description: "Minimum distance to the machining plate."
      exit_depth_min:
        type: "string"
        pattern: "^(?:\\d+(?:\\.\\d+)?|\\d+\\/\\d+)(?:mm|cm|in|inch|mil|thou)$"
        default: "0.7mm"
        description: "Minimum depth beyond the bottom of the PCB from the tip of the bit."
      drillbit_point_angle:
        anyOf:
          - type: "number"
          - type: "string"
            pattern: "^(?:\\d+(?:\\.\\d+)?)(?:°)$"
        default: 135
        description: "Drillbit endpoint geometry angle in degrees."
        minimum: 0
        maximum: 180
      slot_peck_drilling:
        type: object
        properties:
          max_length_to_bit_diameter:
            anyOf:
              - type: "number"
              - type: "string"
                pattern: "^(?:\\d+(?:\\.\\d+)?)(?:.*)$"
            default: 4
            description: "Limit the peck drilling to small slots only."
            minimum: 0
          pecks_per_hole:
            anyOf:
              - type: "number"
              - type: "string"
                pattern: "^(?:\\d+(?:\\.\\d+)?)(?:.*)$"
            default: 4
            description: "Number of pecks in 1 hole."
            minimum: 1
        required: [max_length_to_bit_diameter, pecks_per_hole]
        description: "Setup for peck drilling slots or oblong holes."
      oversizing_allowance_percent:
        anyOf:
          - type: "number"
          - type: "string"
            pattern: "^(?:\\d+(?:\\.\\d+)?)(?:%)$"
        default: 5
        description: "Allowance for drilling a slightly larger hole."
        minimum: 0
      downsizing_allowance_percent:
        anyOf:
          - type: "number"
          - type: "string"
            pattern: "^(?:\\d+(?:\\.\\d+)?)(?:%)$"
        default: 10
        description: "Allowance for drilling a slightly smaller hole."
        minimum: 0
      router_diameter_for_contour:
        type: "string"
        pattern: "^(?:\\d+(?:\\.\\d+)?|\\d+\\/\\d+)(?:mm|cm|in|inch|mil|thou)$"
        default: "1.6mm"
        description: "Preferred routing bit size for routing the contour of the board."
    required: [spindle_speed, z_feedrate, safe_distance, exit_depth_min, drillbit_point_angle, slot_peck_drilling, oversizing_allowance_percent, downsizing_allowance_percent, router_diameter_for_contour]
    description: "Global setup for all tasks."

  stock:
    type: object
    properties:
      drillbits:
        type: object
        properties:
          sizes:
            type: array
            items:
              anyOf:
                - type: "number"
                - type: "string"
                  pattern: "^(?:\\d+(?:\\.\\d+)?|\\d+\\/\\d+)(?:mm|cm|in|inch|mil|thou)$"
            default:
              - 0.35
              - 0.4
              - 0.45
              - 0.5
              - 0.6
              - 0.7
              - 0.8
              - 0.9
              - 1.0
              - 1.1
              - 1.2
              - 1.3
              - 1.4
              - 1.5
              - 1.6
              - 1.7
              - 1.8
              - 1.9
              - 2.0
              - 2.2
              - 2.4
              - 2.6
              - 2.8
              - 3.0
              - 3.1
              - "1/8in"
        description: "List available drillbit sizes."
    required: [drillbits]
    description: "Describe consumable items available from your stock."
