$schema: http://json-schema.org/draft-07/schema#
type: object
description: |
  This file is written Yaml (Yaml.org)

  Scalars can be specified as numbers or strings.
   - Numbers are always interpreted as metric ('mm', 'mm/min' or 'rpm')
   - Strings can have units and fractions:
       . Valid units for sizes are 'cm', 'mm', 'in', 'inch', 'mil' or 'thou'
       . Valid feedrate units are 'mm/min', 'mm/s', 'in/min' or 'ipm'
       - Example: 4um, 12.4mm 23/64in, 100in/min, 24000rpm, 12deg

properties:
  resolution:
    description: |
      Specify the best achievable resolution on the CNC
      All numbers will be rounded to this resolution going forward.
      The value defaults to um
    unit: length(um)
    anyOf:
      - type: number
      - &length_string
        type: "string"
        pattern: "^(?:\\d+(?:\\.\\d+)?|\\d+\\/\\d+)(?:nm|um|mm|cm|in|inch|mil|thou)$"
    default: 1um
  spindle_speed:
    type: object
    properties:
      min:
        description: "Minimum spindle speed in RPM"
        unit: rpm
        anyOf:
          - type: "number"
          - &rpm_string
            type: "string"
            pattern: "^(?:\\d+(?:\\.\\d+)?)(?:rpm)$"
        default: 10000
        minimum: 0
      max:
        description: "Maximum spindle speed in RPM"
        unit: rpm
        anyOf:
          - type: number
          - *rpm_string
        default: 24000
        minimum: 0
    required: [min, max]
    description: "Practical spindle limits in RPM"
  feedrates:
    description: Practical CNC feedrate limits during machining
    type: object
    properties:
      z:
        description: Practical limits to the Z (vertical) feedrates
        type: object
        properties:
          min:
            description: Keep Z feedrate above this value
            unit: feedrate
            anyOf:
              - type: number
              - &feedrate_string
                type: "string"
                pattern: "^(?:\\d+(?:\\.\\d+)?)(?:mm\\/min|cm\\/min|in\\/min|inch\\/min|ipm)$"
            default: 200
            minimum: 0
          max:
            description: Do not exceed the feedrate for the Z axis
            unit: feedrate
            anyOf:
              - type: number
              - *feedrate_string
            default: 4000
            minimum: 0
        required: [min, max]
      xy:
        description: Practical limits to the XY (lateral) feedrates
        type: object
        properties:
          min:
            description: Keep lateral feed rate above this value
            unit: feedrate
            anyOf:
              - type: number
              - *feedrate_string
            default: 200
            minimum: 0
          max:
            description: Keep lateral feed rate below this value
            unit: feedrate
            anyOf:
              - type: number
              - *feedrate_string
            default: 4000
            minimum: 0
        required: [min, max]
    required: [xy, z]
  safe_distance:
    description: Minimum distance to the machining plate
    unit: length
    anyOf:
      - type: number
      - *length_string
    default: "0.5mm"
  exit_depth_min:
    description: Minimum depth beyond the bottom of the PCB from the tip of the bit
    unit: length
    anyOf:
      - type: number
      - *length_string
    default: 0.7mm
  retract_height:
    description: |
      Z distance to retract to between machining operations
      that is the distance from the top of the board upwards.
      If you have a pressure place, this distance should allow the plate
      to spring back to neutral position and to allow for hovering over
      any fixtures on the table
    unit: length
    anyOf:
      - type: number
      - *length_string
    default: 10mm
  drillbit_point_angle:
    description: "Drillbit endpoint geometry angle in degrees"
    unit: angle
    anyOf:
      - type: number
      - type: string
        pattern: "^(?:\\d+(?:\\.\\d+)?)(?:deg|degree)$"
    default: 135
    minimum: 30
    maximum: 180
  slot_peck_drilling:
    description: "Setup for peck drilling slots or oblong holes"
    type: object
    properties:
      max_length_to_bit_diameter:
        description: "Limit the peck drilling to small slots only"
        type: "number"
        default: 4
        minimum: 0
      pecks_per_hole:
        description: "Number of pecks in 1 hole."
        type: "number"
        default: 4
        minimum: 1
    required: [max_length_to_bit_diameter, pecks_per_hole]
  oversizing_allowance_percent:
    description: "Allowance for drilling a slightly larger hole"
    anyOf:
      - &percent_number
        type: "number"
        minimum: 0
        maximum: 200
      - &percent_string
        type: "string"
        pattern: "^(?:0*\\d{1,2}|0*1\\d{2}|0*200)%?$"
    default: 5
    minimum: 0
  downsizing_allowance_percent:
    description: "Allowance for drilling a slightly smaller hole"
    anyOf:
      - *percent_number
      - *percent_string
    default: 10
    minimum: 0
  router_diameter_for_contour:
    description: "Preferred routing bit size for routing the contour of the board"
    unit: length
    anyOf:
      - type: number
      - *length_string
    default: 1.6mm
  backboard_thickness:
    description: "Thickness of the back/martyr/exit-board"
    unit: length
    default: 2.5mm
  gcode:
    description: Configuration around GCode production
    type: object
    properties:
      strip_comments:
        description: Strip all comments
        type: boolean
        default: False
      line_numbers_increment:
        description: Increment line numbering by this number. If 0, turn off line numbering
        default: 10
        type: number
        minimum: 0
        maximum: 1000

required: [resolution, spindle_speed, feedrates, safe_distance, exit_depth_min, drillbit_point_angle, slot_peck_drilling, oversizing_allowance_percent, downsizing_allowance_percent, router_diameter_for_contour, backboard_thickness, gcode]
